[versions]

# https://developer.android.com/studio/releases/gradle-plugin
android-gradle = "7.0.3"

# https://github.com/google/bundletool/releases
bundletool = "1.8.0"

# https://github.com/google/desugar_jdk_libs
desugar = "1.1.5"

# https://kotlinlang.org/docs/releases.html#release-details
kotlin = "1.6.0"

# https://github.com/Kotlin/kotlinx.coroutines/releases
kotlinx-coroutines = "1.5.0"

# https://github.com/google/ksp/releases
ksp = "1.5.20-1.0.0-beta04"

# https://github.com/pinterest/ktlint/releases
ktlint = "0.41.0"

# https://github.com/square/moshi/blob/master/CHANGELOG.md
moshi = "1.12.0"

# https://junit.org/junit4/
junit4 = "4.13.2"

# https://github.com/mockito/mockito/releases
mockito-Core = '3.11.2'

# https://github.com/mockito/mockito-kotlin/releases
mockito-kotlin = '3.2.0'

# https://github.com/robolectric/robolectric/releases/
robolectric = "4.6.1"

[libraries]

android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }

junit4 = { module = "junit:junit", version.ref = "junit4" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ktlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }

kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-test-junit =  { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin"}

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-rx2 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-rx3 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx3", version.ref = "kotlinx-coroutines" }

moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-Core" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito-Core" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }

robolectric-Core = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
robolectric-shadows-httpclient = { module = "org.robolectric:shadows-httpclient", version.ref = "robolectric" }
robolectric-shadows-playservices = { module = "org.robolectric:shadows-playservices", version.ref = "robolectric" }
